<div style="text-align: center; padding: 20px;">
    <img src="austin-distel-744oGeqpxPQ-unsplash.jpeg" alt="​​Subscription Renewal Insights for a SaaS Company" width="450"/>
</div>


<!-- Image source - https://unsplash.com/photos/person-using-macbook-pro-744oGeqpxPQ
-->

    
A SaaS company seeks to uncover what drives its clients to renew subscriptions. They’ve collected data on client details, subscription records, and economic indicators and would like to connect them to better understand its clients’ behavior. 

They’ve tasked you with analyzing these datasets to identify the key factors influencing clients’ decisions to renew their subscriptions. 

Your analysis will provide them with insights into which customers are renewing their products and the reasons behind their renewals. The company can leverage these insights to make informed decisions to increase renewal rates and improve customer loyalty, helping them stay competitive and ensure long-term growth.


## The Data

The company have provided you with three datasets for your analysis. A summary of each data is provided below.

## `client_details.csv`

| Column         | Description|
|----------------|---------------------------------------------------------------|
| `client_id`    | Unique identifier for each client. |
| `company_size` | Size of the company (Small, Medium, Large).|
| `industry`     | Industry to which the client belongs (Fintech, Gaming, Crypto, AI, E-commerce).|
| `location`     | Location of the client (New York, New Jersey, Pennsylvania, Massachusetts, Connecticut).|

## `subscription_records.csv`

| Column             | Description   |
|--------------------|---------------|
| `client_id`        | Unique identifier for each client.|
| `subscription_type`| Type of subscription (Yearly, Monthly).|
| `start_date`       | Start date of the subscription - YYYY-MM-DD.|
| `end_date`         | End date of the subscription - YYYY-MM-DD.|
| `renewed`          | Indicates whether the subscription was renewed (True, False).|

## `economic_indicators.csv`

| Column           | Description                                       |
|------------------|---------------------------------------------------|
| `start_date`     | Start date of the economic indicator (Quarterly) - YYYY-MM-DD.|
| `end_date`       | End date of the economic indicator (Quarterly) - YYYY-MM-DD.|
| `inflation_rate` | Inflation rate in the period.|
| `gdp_growth_rate`| Gross Domestic Product (GDP) growth rate in the period.|

In [35]:
# Re-run this cell
# Import required libraries
import pandas as pd

# Import data
client_details = pd.read_csv('data/client_details.csv')
subscription_records = pd.read_csv('data/subscription_records.csv', parse_dates = ['start_date','end_date'])
economic_indicators = pd.read_csv('data/economic_indicators.csv', parse_dates = ['start_date','end_date'])

In [36]:
client_details.head()

    client_id company_size    industry       location
0  4280387012        Large     Fintech       New York
1  2095513148        Small     Fintech     New Jersey
2  7225516707       Medium     Fintech   Pennsylvania
3  8093537819        Large      Crypto       New York
4  4387541014       Medium  E-commerce  Massachusetts

In [37]:
total_fintech_crypto_clients = client_details[
    (client_details["industry"] == "Fintech") |
    (client_details["industry"] == "Crypto")
].shape[0]
print(total_fintech_crypto_clients)

47

In [38]:
subscription_records.head()

    client_id subscription_type start_date   end_date  renewed
0  1131383004            Yearly 2020-11-11 2021-11-11    False
1  4309371709           Monthly 2021-05-24 2021-06-23     True
2  3183675157            Yearly 2021-12-25 2022-12-25     True
3  5371694837           Monthly 2020-03-14 2020-04-13     True
4  5157113076           Monthly 2019-11-07 2019-12-07    False

In [39]:
subscriptions = pd.merge(subscription_records, client_details, on = 'client_id', how = 'left')
industry_renewal_rates = subscriptions.groupby('industry')['renewed'].mean()
top_industry = industry_renewal_rates.sort_values(ascending = False).index[0]
print(top_industry)

Gaming

In [40]:
economic_indicators.head()

   Unnamed: 0 start_date   end_date  inflation_rate  gdp_growth_rate
0           0 2018-01-01 2018-03-31            5.77             3.51
1           1 2018-04-01 2018-06-30            1.17             2.15
2           2 2018-07-01 2018-09-30            1.56             1.82
3           3 2018-10-01 2018-12-31            2.78             2.43
4           4 2019-01-01 2019-03-31            6.91             3.44

In [41]:
subscriptions_with_inflation = pd.merge_asof(subscription_records.sort_values(by='end_date'), 
                                             economic_indicators, 
                                             left_on='end_date', 
                                             right_on='start_date', 
                                             direction='backward')
average_inflation_for_renewals = subscriptions_with_inflation[subscriptions_with_inflation['renewed'] == True].inflation_rate.mean()
print(average_inflation_for_renewals)

4.418909090909092