<center><img src="trainers.jpg" alt="Trainers in a store" width=550></center>

Sports clothing and athleisure attire is a huge industry, worth approximately $193 billion in 2021 with a strong growth forecast over the next decade! (`Source: https://www.statista.com/statistics/254489/total-revenue-of-the-global-sports-apparel-market/`)

In this workbook, you will undertake the role of a product analyst for an online sports clothing company. The company is specifically interested in how it can improve revenue. You will dive into product data such as pricing, reviews, descriptions, and ratings, as well as revenue and website traffic, to produce recommendations for its marketing and sales teams.  

### The data:
You've been provided with four datasets to investigate:

`brands.csv`

| Columns | Description |
|---------|-------------|
| `product_id` | Unique product identifier |
| `brand` | Brand of the product | 

`finance.csv`

| Columns | Description |
|---------|-------------|
| `product_id` | Unique product identifier |
| `listing_price` | Original price of the product | 
| `sale_price` | Discounted price of the product |
| `discount` | Discount off the listing price, as a decimal | 
| `revenue` | Revenue generated by the product |

`info.csv`

| Columns | Description |
|---------|-------------|
| `product_name` | Name of the product | 
| `product_id` | Unique product identifier |
| `description` | Description of the product |

`reviews.csv`

| Columns | Description |
|---------|-------------|
| `product_id` | Unique product identifier |
| `rating` | Average product rating | 
| `reviews` | Number of reviews for the product |

In [32]:
# Importing libraries
import pandas as pd

# Loading the data
brands = pd.read_csv("brands.csv") 
finance = pd.read_csv("finance.csv")
info = pd.read_csv("info.csv")
reviews = pd.read_csv("reviews.csv")

# Start coding here...

In [33]:
brands.head()

  product_id   brand
0     AH2430     NaN
1     G27341  Adidas
2     CM0081  Adidas
3     B44832  Adidas
4     D98205  Adidas

In [34]:
finance.head()

  product_id  listing_price  sale_price  discount  revenue
0     AH2430            NaN         NaN       NaN      NaN
1     G27341          75.99       37.99       0.5  1641.17
2     CM0081           9.99        5.99       0.4   398.93
3     B44832          69.99       34.99       0.5  2204.37
4     D98205          79.99       39.99       0.5  5182.70

In [35]:
info.head()

                                       product_name  ...                                        description
0                                               NaN  ...                                                NaN
1              Women's adidas Originals Sleek Shoes  ...  A modern take on adidas sport heritage, tailor...
2                 Women's adidas Swim Puka Slippers  ...  These adidas Puka slippers for women's come wi...
3  Women's adidas Sport Inspired Questar Ride Shoes  ...  Inspired by modern tech runners, these women's...
4          Women's adidas Originals Taekwondo Shoes  ...  This design is inspired by vintage Taekwondo s...

[5 rows x 3 columns]

In [36]:
reviews.head()

  product_id  rating  reviews
0     AH2430     NaN      NaN
1     G27341     3.3     24.0
2     CM0081     2.6     37.0
3     B44832     4.1     35.0
4     D98205     3.5     72.0

In [37]:
merged_df = info.merge(finance, on="product_id")
merged_df = merged_df.merge(reviews, on="product_id")
merged_df = merged_df.merge(brands, on="product_id")
merged_df.dropna(inplace=True)

In [38]:
merged_df.head()

                                        product_name  ...   brand
1               Women's adidas Originals Sleek Shoes  ...  Adidas
2                  Women's adidas Swim Puka Slippers  ...  Adidas
3   Women's adidas Sport Inspired Questar Ride Shoes  ...  Adidas
4           Women's adidas Originals Taekwondo Shoes  ...  Adidas
5  Women's adidas Sport Inspired Duramo Lite 2.0 ...  ...  Adidas

[5 rows x 10 columns]

In [39]:
twenty_fifth = merged_df["listing_price"].quantile(0.25)
median = merged_df["listing_price"].quantile(0.5)
seventy_fifth = merged_df["listing_price"].quantile(0.75) 
maximum = merged_df["listing_price"].max()
merged_df["price_label"] = pd.cut(merged_df["listing_price"], bins=[0, twenty_fifth, median, seventy_fifth, maximum], labels=["Budget", "Average", "Expensive", "Elite"], include_lowest=True)

In [40]:
merged_df.head()

                                        product_name  ... price_label
1               Women's adidas Originals Sleek Shoes  ...   Expensive
2                  Women's adidas Swim Puka Slippers  ...      Budget
3   Women's adidas Sport Inspired Questar Ride Shoes  ...   Expensive
4           Women's adidas Originals Taekwondo Shoes  ...   Expensive
5  Women's adidas Sport Inspired Duramo Lite 2.0 ...  ...     Average

[5 rows x 11 columns]

In [41]:
adidas_vs_nike = merged_df.groupby(["brand", "price_label"], as_index=False).agg(
    num_products=("price_label", "count"), 
    mean_revenue=("revenue", "mean")
).round(2)

In [42]:
print(adidas_vs_nike)

    brand price_label  num_products  mean_revenue
0  Adidas      Budget           574       2015.68
1  Adidas     Average           655       3035.30
2  Adidas   Expensive           759       4621.56
3  Adidas       Elite           587       8302.78
4    Nike      Budget           357       1596.33
5    Nike     Average             8        675.59
6    Nike   Expensive            47        500.56
7    Nike       Elite           130       1367.45

In [43]:
merged_df["description_length"] = merged_df["description"].str.len()

In [44]:
lengthes = [0, 100, 200, 300, 400, 500, 600, 700]
labels = ["100", "200", "300", "400", "500", "600", "700"]
merged_df["description_length"] = pd.cut(merged_df["description_length"], bins=lengthes, labels=labels)

In [45]:
description_lengths = merged_df.groupby("description_length", as_index=False).agg(
    mean_rating=("rating", "mean"), 
    total_reviews=("reviews", "sum")
).round(2)

print(description_lengths)

  description_length  mean_rating  total_reviews
0                100         2.26           36.0
1                200         3.19        17719.0
2                300         3.28        76115.0
3                400         3.29        28994.0
4                500         3.35         4984.0
5                600         3.12          852.0
6                700         3.65          818.0